# Generated by Django 3.0.5 on 2020-04-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='email_address',
            field=models.EmailField(default=20, max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='id_number',
            field=models.IntegerField(default=13),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='surname',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
