# Generated by Django 3.0.5 on 2020-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200418_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='surname',
            field=models.TextField(max_length=50),
        ),
    ]
