# Generated by Django 3.0.5 on 2020-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200418_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='id_number',
            field=models.IntegerField(),
        ),
    ]
