# Generated by Django 3.0.5 on 2020-04-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200418_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='post',
            name='surname',
        ),
    ]
