# Generated by Django 3.0.5 on 2020-04-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200418_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='surnamename',
            field=models.TextField(default=None),
        ),
    ]
