# Generated by Django 3.0.5 on 2020-04-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_surnamename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='surnamename',
        ),
    ]
