# Generated by Django 3.0.5 on 2020-04-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_post_surnamename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='text',
        ),
    ]
