# Generated by Django 3.0.5 on 2020-04-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20200418_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='surname',
            field=models.TextField(default=None),
        ),
    ]
