# Generated by Django 3.0.5 on 2020-04-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20200418_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Email',
            field=models.IntegerField(default=None),
        ),
    ]
