# Generated by Django 3.0.5 on 2020-04-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Address',
            field=models.TextField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='CellNumber',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='PassWord',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='PostalCode',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='UserName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='id_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='Email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='surname',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
