# Generated by Django 3.0.5 on 2020-04-13 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200412_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, null=True)),
                ('date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
