# Generated by Django 3.0.5 on 2020-04-13 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200413_0508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registration',
        ),
    ]
