# Generated by Django 3.0.5 on 2020-04-13 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200413_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('surnamename', models.TextField(max_length=255)),
                ('id_number', models.IntegerField()),
                ('cellnumber', models.CharField(max_length=255)),
                ('date_of_reg', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
