# Generated by Django 3.0.5 on 2020-04-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200413_0530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registration',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='surnamename',
            new_name='surname',
        ),
    ]
